name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
 
      - name: Run tests
        run: npm run test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Coverage check
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min_coverage: 90
